name: CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python validate_labels.py --path data/ls_export_sample.csv --format csv --id-col id --text-col text --label-col label
      - run: python agreement_labels.py --file-a data/ls_export_sample_v2.csv --col-a label --col-b label2